# Generated by Django 5.2.1 on 2026-08-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("resource_id", models.CharField(max_length=512)),
                ("resource_name", models.CharField(max_length=255)),
                (
                    "resource_group",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("cost", models.DecimalField(decimal_places=4, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=8)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="core_costre_date_9d9e2a_idx"),
                    models.Index(
                        fields=["resource_id"], name="core_costre_resourc_e5e581_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "resource_id"),
                        name="unique_cost_record_per_day",
                    )
                ],
            },
        ),
    ]
